### ISSUE TITLE
error 401 when using token of incoming webhook

### ISSUE THREAD

**Issue by sahasrara62** [Tim-Schwalbe/python_mattermost#2]
I am using your script and I have an incoming webhook token, I am using that as token in your code, but I am getting an invalid token error and is unable to send the file to my channel.

I have modified the code, instead of giving the data as an argument, I haved hard code them for now.  

i am getting error 401. can you help me on this.

Thanks

**Comment by Tim-Schwalbe** [comment]
can you post the code? Then I can check it.

**Comment by sahasrara62** [comment]
@Tim-Schwalbe  here are the details



code


     import os
     import json
     import requests
     import argparse
    
    server_url = '' # mattermost server # https://<server>.com
    access_token = '' # incoming webhook token https://<server>.com/hooks/<token> # taken token part here only
    channel_id = 'mattermost_test' # channel name private
    file_path = r""  # image path absolute
    message = "hello world !"
    attachment_message = ''
    color = '#FF8777'
    
    if attachment_message == "":
        props = {}
    else:
        props = {"attachments": [{"text":attachment_message,"color":color}]}
    
    print(props)
    s = requests.Session()
    s.headers.update({"Authorization": "Bearer " + access_token})
    
    form_data = {
        "channel_id": ('', channel_id),
        "client_ids": ('', "id_for_the_file"),
        "files": (os.path.basename(file_path), open(file_path, 'rb')),
    }
    r = s.post(server_url + '/api/v4/files', files=form_data)
    
    FILE_ID = r.json()["file_infos"][0]["id"]
    
    p = s.post(server_url + '/api/v4/posts', data=json.dumps({
        "channel_id": channel_id,
        "message": message,
        "file_ids": [FILE_ID],
        "props": props
    }))
    ``
error

`` Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "C:\Users\prashra\project_data\software\pycharm\PyCharm 2018.3.4\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
        pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
      File "C:\Users\prashra\project_data\software\pycharm\PyCharm 2018.3.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
        exec(compile(contents+"\n", file, 'exec'), glob, loc)
      File "C:/Users/prashra/PycharmProjects/personal_project/mattermost/file.py", line 31, in <module>
        FILE_ID = r.json()["file_infos"][0]["id"]
    KeyError: 'file_infos'``

**Comment by sahasrara62** [comment]
alternatly i have tried 

        import requests, json
        import base64
        import os
        
        URL = "https://matter.i.daimler.com/hooks/ppnyry11wjnuzgmt756orimfor"
        file_path = r'C:\Users\prashra\PycharmProjects\personal_project\mattermost\requiremnets.txt'
        z=open(file_path,'rb')
        k=z.read()
        print(k)
        form_data = {
                     "files": (os.path.basename(file_path), z)
                     }
        
        payload = {"channel_id": "mattermost_test", "display_name": "i dont know", "text": "holy"}
        headers = {"Content-Type": "application/json"}
        # files = {'files': ('2.jpg', z)}
        print(payload)
        payload.update(form_data)
        print(payload)
        r = requests.post(URL, data=json.dumps(payload), headers=headers,json=file_path)

getting this error 


       TypeError: Object of type BufferedReader is not JSON serializable

can you help me on this

@Tim-Schwalbe

**Comment by sahasrara62** [comment]
alternatly i have tried 

        import requests, json
        import base64
        import os
        
        URL = ""
        file_path = r'C:\Users\prashra\PycharmProjects\personal_project\mattermost\requiremnets.txt'
        z=open(file_path,'rb')
        k=z.read()
        print(k)
        form_data = {
                     "files": (os.path.basename(file_path), z)
                     }
        
        payload = {"channel_id": "mattermost_test", "display_name": "i dont know", "text": "holy"}
        headers = {"Content-Type": "application/json"}
        # files = {'files': ('2.jpg', z)}
        print(payload)
        payload.update(form_data)
        print(payload)
        r = requests.post(URL, data=json.dumps(payload), headers=headers,json=file_path)

getting this error 


       TypeError: Object of type BufferedReader is not JSON serializable

can you help me on this

@Tim-Schwalbe

**Comment by Tim-Schwalbe** [comment]
can you try it with a file relative to your project, maybe the windows path is not recognized. For me this looks like an issue with the file. I use the code in the repo everyday with images.

see this: `os.path.basename(file_path)` this could be the issue.

**Comment by sahasrara62** [comment]
thanks, it helps, I was also considering channel_id as channel name, it is not same as channel name, need to search to get the channel id.
